version: '3.8'
name: burger_fullstack

services:
  db:
    image: postgres:16-alpine
    container_name: db
    environment:
      POSTGRES_USER: burger
      POSTGRES_PASSWORD: burger
      POSTGRES_DB: burgerdb
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: backend
    environment:
      DB_URL: postgresql+psycopg2://burger:burger@db:5432/burgerdb
      JWT_SECRET: dev-secret-change-me
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

  e2e:
    image: python:3.12-slim
    container_name: e2e
    depends_on:
      - backend
      - frontend
    entrypoint: ["bash", "-lc", "python /e2e/e2e.py"]
    volumes:
      - ./e2e:/e2e

volumes:
  db_data:
