[project]
name = "Burger-kiosk"
version = "0.1.0"
description = "FastAPI-based burger kiosk with Kafka message queue"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "confluent-kafka>=2.12.0",
    "fastapi[standard]>=0.119.0",
]
